---

- name: Prepare admin resources
  hosts: undercloud
  gather_facts: False
  vars:
    user: true
    net_port: false
    keypair: false
    security_group: false
    resource_state: present
  vars_files: "{{ admin_resources | mandatory }}"
  roles:
    - post_install/openstack_tasks

- name: Prepare tenant resources
  hosts: undercloud
  gather_facts: False
  vars:
    setup_os_env: false
    flavor: false
    image: false
    instance: true
    resources_output: true
    resource_state: present
  vars_files: "{{ tenant_resources | mandatory }}"
  roles:
    - post_install/openstack_tasks

- name: Tempest deployment and execution
  hosts: tester
  gather_facts: False
  roles:
    - tester/tempest

- name: Delete tenant resources
  hosts: undercloud
  gather_facts: False
  vars:
    setup_os_env: false
    flavor: false
    image: false
    instance: true
    resources_output: true
    resource_state: absent
  vars_files: "{{ tenant_resources | mandatory }}"
  roles:
    - post_install/openstack_tasks

- name: Delete admin resources
  hosts: undercloud
  gather_facts: False
  vars:
    setup_os_env: false
    user: true
    net_port: false
    keypair: false
    security_group: false
    resource_state: absent
  vars_files: "{{ admin_resources | mandatory }}"
  roles:
    - post_install/openstack_tasks

  tasks:
    - name: Print the output results of the tempest tests
      vars:
        tempest_dir: /home/stack/tempest
        msg: |
          Tests statistics:

          {{ tests_stats.stdout }}

          For the details, look at the:
          {{ tempest_dir }}/tempest.xml
          {{ tempest_dir }}/tempest.log
      debug:
        msg: "{{ msg.split('\n') }}"
