---

- name: Collect data of pre-existing resources
  hosts: localhost
  gather_facts: False
  tasks:

    - name: Use Pre-existing Resources
      block:
        - name: Prepare Virtual Environment
          include_role:
            name: openstack_tasks
            tasks_from: setup_openstack_env

        - name: Add Pre-existing Instances To Dynamic Inventory
          include_role:
            name: dynamic_host_inventory
          loop: "{{ dynamic_instances }}"

- name: Collect data from trex
  hosts: trex
  tasks:
    - name: Collect only facts returned by facter
      ansible.builtin.setup:
        gather_subset:
          - "!all"
          - architecture
          - cmdline
          - devices
          - distribution
          - hardware
          - processor
          - facter
      register: trex_info_t
      become: true
    - name: Set trex_info fact
      set_fact:
        trex_info: "{{ trex_info_t }}"
      delegate_to: localhost
      delegate_facts: true

- name: Collect data from localhost
  hosts: localhost
  gather_facts: False
  tasks:
    - block:
        - name: Collect only facts returned by facter
          ansible.builtin.setup:
            gather_subset:
              - "!all"
              - architecture
              - cmdline
              - devices
              - distribution
              - hardware
              - processor
              - facter
          register: compute_info
          become: true

        - name: Get NICs info
          ansible.builtin.shell: lshw -json -c network | jq ".[] | .product" | sed 's/"//g'
          register: compute_nics

        - name: Get OVS version
          ansible.builtin.command: ovs-vswitchd --version
          register: compute_ovs_versions

      delegate_to: "{{ dut_compute if dut_compute else 'none' }}"

    - name: Upload result to elk
      include_role:
        name: packet_gen/trex/upload_results_to_elk
