---
- name: Destroy
  hosts: undercloud
  gather_facts: false
  vars:
    inventory_generated: "{{ lookup('env', 'TEST_INV_GENERATED') }}"
  tasks:
    - name: Delete tempest directory
      file:
        path: "{{ item }}"
        state: absent
      loop:
        - /home/stack/etc
        - /home/stack/tempest

    - name: Delete NFV container
      containers.podman.podman_container:
        name: nfv-tempest
        state: absent

    - name: Delete NFV container image
      containers.podman.podman_image:
        name: quay.io/rhos-dfg-nfv/tempest-nfv-plugin
        state: absent

    - block:
        - name: Delete created inventory
          file:
            path: "{{ item }}"
            state: absent
          loop:
            - inventory
            - ansible.ssh.config
            - environments
          delegate_to: localhost

        - name: Restore dump inventory
          copy:
            content: 'localhost ansible_connection=local'
            dest: inventory
            mode: 0664
          delegate_to: localhost
      when: not inventory_generated
