---

- name: Prepare the environment
  hosts: controller
  vars:
    setup_os_env: true
    create_networks: true
    create_flavors: true
    images_upload: false
  roles:
    - post_install/openstack_tasks

- name: Tempest deployment and execution
  hosts: tester
  roles:
    - tester/tempest
