---

- name: Change "prevent_arp_spoofing" to False
  ini_file:
    dest: "/etc/neutron/plugins/ml2/openvswitch_agent.ini"
    section: 'agent'
    option: 'prevent_arp_spoofing'
    value: 'false'
  notify:
    - 'Restart openvswitch agent service'
    - 'Restart openvswitch service'
