- name: Check Undercloud version
  import_tasks: undercloud.yml
  delegate_to: "{{ groups['undercloud'] | first }}"

- name: Check Overcloud version
  import_tasks: overcloud.yml
  delegate_to: "{{ groups['overcloud_nodes'] | first }}"
