---

# NOTE: In Ocata version, the following task fails before finishing
#       the delete process of the stack.
#       As a workaroung, 'ignore_errors' flag and 'pause' task added.
# TODO: Once fixed, remove this.
- name: Delete Overcloud stack
  vars:
    ansible_python_interpreter: "{{ venv_path }}/bin/python"
  os_stack:
    cloud: "{{ cloud_name }}"
    name: "{{ overcloud_name | default('overcloud') }}"
    state: absent
    wait: yes
    cacert: "{{ client_ca_cert | default(omit) }}"
  ignore_errors: true

- name: Pause the play, wait until stack deleted completely
  pause:
    minutes: 3
