---

# Tags
setup_os_env: true
user: false
net_port: true
quota: true
flavor: true
network: true
image: true
instance: true
aggregate: true
resources_output: false
overcloud_name: overcloud

# User creation
users:
  - name: admin
    project: admin
    role: admin
    quota:
      - cores: 40

# Network creation
networks:
  - name: 'external_net_423'
    physical_network: 'access'
    segmentation_id: '423'
    allocation_pool_start: '10.35.185.81'
    allocation_pool_end: '10.35.185.93'
    cidr: '10.35.185.80/28'
    enable_dhcp: true
    gateway_ip: '10.35.185.94'
    network_type: vlan
    external: true
    shared: true
    router_name: router

  - name: 'management_net_137'
    allocation_pool_start: '10.10.137.100'
    allocation_pool_end: '10.10.137.200'
    cidr: '10.10.137.0/24'
    enable_dhcp: true
    gateway_ip: '10.10.137.254'
    network_type: vxlan
    external: false
    router_name: router

  - name: 'dpdk_net_nic0_138'
    physical_network: dpdk-data0
    segmentation_id: '138'
    allocation_pool_start: '10.10.138.100'
    allocation_pool_end: '10.10.138.200'
    cidr: '10.10.138.0/24'
    enable_dhcp: false
    gateway_ip: '10.10.138.254'
    network_type: vlan

  - name: 'dpdk_net_nic1_139'
    physical_network: dpdk-data1
    segmentation_id: '139'
    allocation_pool_start: '10.10.139.100'
    allocation_pool_end: '10.10.139.200'
    cidr: '10.10.139.0/24'
    enable_dhcp: false
    gateway_ip: '10.10.139.254'
    network_type: vlan

  - name: 'sriov_net_nic0_138'
    physical_network: sriov-1
    segmentation_id: '138'
    allocation_pool_start: '10.10.138.100'
    allocation_pool_end: '10.10.138.200'
    cidr: '10.10.138.0/24'
    enable_dhcp: false
    gateway_ip: '10.10.138.254'
    network_type: vlan

  - name: 'sriov_net_nic1_139'
    physical_network: sriov-2
    segmentation_id: '139'
    allocation_pool_start: '10.10.139.100'
    allocation_pool_end: '10.10.139.200'
    cidr: '10.10.139.0/24'
    enable_dhcp: false
    gateway_ip: '10.10.139.254'
    network_type: vlan

dns_nameservers:
  - 10.46.0.31
  - 8.8.8.8

# Aggregate group creation
aggregate_groups:
  - name: TREX_AG
    hosts:
      - computeovsdpdksriov-0.localdomain
    metadata:
      - flavor=trex_ag

  - name: DUT_AG
    hosts:
      - computeovsdpdksriov-1.localdomain
    metadata:
      - flavor=dut_ag

# Flavor creation
flavors:
  - name: perf_numa_0_trex
    ram: 8192
    disk: 20
    vcpus: 16
    extra_specs:
      "hw:mem_page_size": "1GB"
      "hw:cpu_policy": "dedicated"
      "hw:numa_nodes": "1"
      "hw:numa_cpus.0": "0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15"
      "hw:numa_mem.0": "8192"
      "hw:emulator_threads_policy": "share"
      "aggregate_instance_extra_specs:flavor": "trex_ag"

  - name: perf_numa_0_sriov_dut
    ram: 8192
    disk: 20
    vcpus: 16
    extra_specs:
      "hw:mem_page_size": "1GB"
      "hw:cpu_policy": "dedicated"
      "hw:numa_nodes": "1"
      "hw:numa_cpus.0": "0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15"
      "hw:numa_mem.0": "8192"
      "hw:emulator_threads_policy": "share"
      "aggregate_instance_extra_specs:flavor": "dut_ag"

  - name: perf_numa_1_dpdk_dut
    ram: 8192
    disk: 20
    vcpus: 8
    extra_specs:
      "hw:mem_page_size": "1GB"
      "hw:cpu_policy": "dedicated"
      "hw:numa_nodes": "1"
      "hw:numa_cpus.1": "0,1,2,3,4,5,6,7"
      "hw:numa_mem.1": "8192"
      "hw:emulator_threads_policy": "share"
      "aggregate_instance_extra_specs:flavor": "dut_ag"

# Image upload to the environment
images:
  - name: trex_testpmd
    url: http://file.tlv.redhat.com/~vkhitrin/nfv_tuned_rhel76.qcow2

# Allow ICPM and SSH access to instances
security_groups:
  - name: test_secgroup
    rules:
      - protocol: icmp
        port_range_min: -1
        port_range_max: -1
        remote_ip_prefix: 0.0.0.0/0
      - protocol: tcp
        port_range_min: 22
        port_range_max: 22
        remote_ip_prefix: 0.0.0.0/0

# Instances creation
instances:
  - name: trex
    groups: trex
    flavor:  perf_numa_0_trex
    image: trex_testpmd
    key_name: test_keypair
    sec_groups: test_secgroup
    config_drive: true
    floating_ip:
      ext_net: external_net_423
      int_net: management_net_137
    nics:
      - net-name=management_net_137
      - port-name=sriov_net_nic0_138_trex_direct-physical_port-0
      - port-name=sriov_net_nic1_139_trex_direct-physical_port-1
    net_ports:
      - name: sriov_net_nic0_138_trex_direct-physical_port-0
        network: sriov_net_nic0_138
        port_security: false
        type: direct-physical
      - name: sriov_net_nic1_139_trex_direct-physical_port-1
        network: sriov_net_nic1_139
        port_security: false
        type: direct-physical

  - name: testpmd-sriov-vf-dut
    groups: sriov_dut
    flavor: perf_numa_0_sriov_dut
    image: trex_testpmd
    key_name: test_keypair
    sec_groups: test_secgroup
    config_drive: true
    floating_ip:
      ext_net: external_net_423
      int_net: management_net_137
    nics:
      - net-name=management_net_137
      - port-name=sriov_net_nic0_138_sriov_vf_dut_direct_port-0
      - port-name=sriov_net_nic1_139_sriov_vf_dut_direct_port-1
    net_ports:
      - name: sriov_net_nic0_138_sriov_vf_dut_direct_port-0
        network: sriov_net_nic0_138
        port_security: false
        type: direct
      - name: sriov_net_nic1_139_sriov_vf_dut_direct_port-1
        network: sriov_net_nic1_139
        port_security: false
        type: direct

  - name: testpmd-dpdk-dut
    groups: dpdk_dut
    flavor: perf_numa_1_dpdk_dut
    image: trex_testpmd
    key_name: test_keypair
    sec_groups: test_secgroup
    config_drive: false
    floating_ip:
      ext_net: external_net_423
      int_net: management_net_137
    nics:
      - net-name=management_net_137
      - port-name=dpdk_net_nic0_138_dpdk_dut_port-0
      - port-name=dpdk_net_nic1_139_dpdk_dut_port-1
    net_ports:
      - name: dpdk_net_nic0_138_dpdk_dut_port-0
        network: dpdk_net_nic0_138
        port_security: false
        type: normal
      - name: dpdk_net_nic1_139_dpdk_dut_port-1
        port_security: false
        network: dpdk_net_nic1_139
        type: normal

# Use exist cloud resources
cloud_resources: external

# DUT compute
dut_compute: computeovsdpdksriov-1

# Trex config
trex_lcores: '3,4,5'
