# Parse trex configuration during run time from trex instance
gather_trex_conf_live: True

# Destination of trex config file
trex_conf_file: '/etc/trex_cfg.yaml'

# Clone trafficgen repo https://github.com/atheurer/trafficgen
clone_traffic_gen_repo: True

# Trafficgen repo URI
trafficgen_repo: 'https://github.com/perftool-incubator/bench-trafficgen'

# Trafficgen branch
trafficgen_branch: 'main'

# Directory where trafficgen repo will be cloned to
# We have to differentiate between `trafficgen_clone_dir` and `trafficgen_dir`
# of binary_search role (which uses this clone) because it could happens (and
# actually happens) that the actual clone directory of trafficgen for
# https://github.com/perftool-incubator/bench-trafficgen is
# `/opt/bench-trafficgen/trafficgen` instead of `/opt/bench-trafficgen` so
# `trafficgen_dir` in binary_search role must be set to
# `/opt/bench-trafficgen/trafficgen`
trafficgen_clone_dir: '/opt/bench-trafficgen'

# Platform sepcific Trex configuration
trex_platform:
  master_thread_id: 2
  latency_thread_id: 3
  dual_if:
    - socket: 0
      threads: [4, 5, 6, 7, 8, 9, 10, 11]

# DPDK root dir
dpdk_root_dir: '/root/dpdk'

# Workaround - can't define this variable inside playbook
trex_full_nic_info: []
