# DPDK directory on host
dpdk_root_dir: '/root/dpdk'

# Compiled DPDK binaries directory
dpdk_compiled_dir: '{{ dpdk_root_dir }}/build/app'

hugepages_count: 4

# dpdk drivers to use: vfio-pci, mlx5_core
dpdk_binding_driver: 'vfio-pci'

# Set to True if profile traffic needs to cross router boundaries, this will
# the destination MAC addresses of outgoing traffic from DUT and TREX to be set
# to the MAC addresses of their corresponding gateways
packet_gen_routed_traffic: False
